// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_BLL.Identity;

#nullable disable

namespace project_DAL.Migrations
{
    [DbContext(typeof(StoreContext))]
    partial class StoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLove")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WhatsappNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("project_BLL.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ResetCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetCodeExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("project_DAL.Entities.BabyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AIName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("prediction")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BabyRecords");
                });

            modelBuilder.Entity("project_DAL.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("project_DAL.Entities.MessageDeleted", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("MessageDeleteds");
                });

            modelBuilder.Entity("project_DAL.Entities.MotherGuids.UserTip", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TipId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "TipId");

                    b.HasIndex("TipId");

                    b.ToTable("UserTip");
                });

            modelBuilder.Entity("project_DAL.Identity.Tip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tips");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2dfb8973-7690-44dd-8560-79b5f8a667a4"),
                            Description = "Ensure your baby receives regular medical check-ups to monitor growth and development. Create a safe and clean environment at home, free from hazards, and always keep emergency contacts easily accessible for peace of mind.",
                            Title = "Baby Care Tips"
                        },
                        new
                        {
                            Id = new Guid("eb607ec9-d45a-4fff-bbab-3b05ef8cd53a"),
                            Description = "Breastfeeding is ideal for the first 6 months, providing essential nutrients and antibodies. When introducing solids, start with pureed fruits and vegetables, and gradually expand to grains and proteins while monitoring for any allergic reactions.",
                            Title = "Nutrition Advice"
                        },
                        new
                        {
                            Id = new Guid("a12a6f26-3013-4d4e-9e7c-023d3c41456b"),
                            Description = "Hold, cuddle, and talk to your baby often to create a strong emotional connection. Skin-to-skin contact, eye contact, and gentle communication help build trust and foster emotional security, which are vital for healthy development.",
                            Title = "Emotional Bonding"
                        },
                        new
                        {
                            Id = new Guid("a38e466a-d93a-47cb-bfef-2787b033709d"),
                            Description = "Baby-proof your home by using outlet covers, installing baby gates, and securing furniture to walls. Keep sharp objects, small items, and cleaning supplies out of reach. Regularly check for potential hazards as your baby becomes more mobile.",
                            Title = "Safety at Home"
                        },
                        new
                        {
                            Id = new Guid("eb4552ee-6583-4be3-a696-dad9bbb1d9d6"),
                            Description = "Establish a consistent bedtime routine that includes calming activities like a warm bath or gentle lullabies. Ensure the sleeping environment is safe and quiet, and place your baby on their back to sleep to reduce the risk of SIDS.",
                            Title = "Healthy Sleep Habits"
                        },
                        new
                        {
                            Id = new Guid("91a0d18f-9120-4f6a-aedd-50013a1f8d22"),
                            Description = "For the first six months, breast milk or formula provides all necessary hydration. After six months, you can gradually introduce small amounts of water, especially in hot weather, while continuing regular milk feedings to maintain proper hydration.",
                            Title = "Hydration Tips"
                        },
                        new
                        {
                            Id = new Guid("88a33343-b7c6-436e-ad4c-98fc9abee9c2"),
                            Description = "Incorporate tummy time into your baby’s daily routine to help strengthen neck, shoulder, and arm muscles. Place your baby on a soft mat under supervision, starting with a few minutes a day and gradually increasing the duration as they grow.",
                            Title = "Tummy Time"
                        },
                        new
                        {
                            Id = new Guid("b5ea1437-215c-4b6c-bc3c-8bb4facf9795"),
                            Description = "Pay close attention to your baby’s different cries, as they often signal specific needs like hunger, sleepiness, or discomfort. Over time, you’ll become better at recognizing these cues, helping you respond quickly and effectively to soothe your baby.",
                            Title = "Understanding Cries"
                        },
                        new
                        {
                            Id = new Guid("0287eb9f-c748-4e61-9a04-b523ee77b4b5"),
                            Description = "Always have a well-stocked first-aid kit at home with essentials like bandages, antiseptics, and a thermometer. Learn basic infant CPR and choking rescue techniques, and keep emergency contact numbers readily available in case of urgent medical situations.",
                            Title = "First Aid Basics"
                        },
                        new
                        {
                            Id = new Guid("b0e1d735-aa51-4343-9a39-5f204aa3b906"),
                            Description = "Begin introducing solids around six months, starting with pureed vegetables and fruits. Gradually add iron-rich foods, grains, and proteins, offering one new food at a time to monitor for allergies. Avoid honey and whole nuts before the age of one.",
                            Title = "Introducing Solids"
                        },
                        new
                        {
                            Id = new Guid("067c23cb-32f2-460b-93c2-d5093005ccc3"),
                            Description = "Spending time outdoors is essential for your baby's physical and mental development. Fresh air, natural light, and safe outdoor activities stimulate the senses and support overall health. Always use appropriate sun protection and stay mindful of weather conditions.",
                            Title = "Outdoor Time"
                        },
                        new
                        {
                            Id = new Guid("0544dd3a-821a-49a3-8817-b2c1df9ef99e"),
                            Description = "Prevent diaper rash by changing diapers frequently and allowing the area to air out. Apply zinc oxide cream as a barrier and use gentle, fragrance-free wipes. If a rash persists or worsens, consult your pediatrician for appropriate treatment options.",
                            Title = "Diaper Rash Care"
                        },
                        new
                        {
                            Id = new Guid("f8fad182-ba29-4152-8353-b800b1470040"),
                            Description = "Follow your pediatrician’s recommended vaccination schedule to protect your baby against preventable diseases. Keep an updated immunization record and stay informed about any additional vaccines that may be needed based on your location or specific health considerations.",
                            Title = "Vaccination Schedule"
                        },
                        new
                        {
                            Id = new Guid("a51414ab-e721-4809-9a00-c7c9a3b182e4"),
                            Description = "Make reading a daily habit to promote language development and cognitive growth. Choose colorful, age-appropriate books and use expressive voices to keep your baby engaged. Reading together also strengthens emotional bonds and fosters a lifelong love for books.",
                            Title = "Reading to Your Baby"
                        },
                        new
                        {
                            Id = new Guid("08acc56b-2c81-48c6-ace5-a5c4c461ad67"),
                            Description = "Teething can be uncomfortable, so offer your baby cold teething rings or a clean, damp washcloth to chew on. Gently massage their gums with your finger and use pediatrician-approved remedies if necessary to help ease their discomfort during this stage.",
                            Title = "Teething Relief"
                        },
                        new
                        {
                            Id = new Guid("877d09dc-292b-4020-b08b-345bcd387a42"),
                            Description = "Track your baby's developmental milestones, such as rolling over, crawling, and first words. Remember that every child develops at their own pace, so use milestones as general guidelines rather than strict deadlines.",
                            Title = "Monitor Milestones"
                        },
                        new
                        {
                            Id = new Guid("82f0ecf3-ec4d-4e4e-a8cd-2530b4340ae0"),
                            Description = "Use positive reinforcement and redirection to guide your baby's behavior. Encourage good habits by praising positive actions, and avoid harsh discipline methods that can negatively impact emotional development and trust.",
                            Title = "Gentle Discipline"
                        },
                        new
                        {
                            Id = new Guid("98f1522d-7f61-4e37-a0ed-dcb004919ec9"),
                            Description = "Maintain a balanced diet rich in vitamins, minerals, and protein to support milk production during breastfeeding. Stay hydrated, avoid excessive caffeine, and consult a healthcare provider for supplements if needed to ensure both you and your baby thrive.",
                            Title = "Breastfeeding Nutrition"
                        },
                        new
                        {
                            Id = new Guid("573b37af-869b-4a96-a8c7-39c16da65157"),
                            Description = "Prioritize rest, hydration, and mental health during postpartum recovery. Accept help from family and friends, take short naps when possible, and seek support if you experience mood changes or feelings of overwhelm during this transitional period.",
                            Title = "Postpartum Self-Care"
                        },
                        new
                        {
                            Id = new Guid("76482033-cd48-4eb0-9373-ea6cea62d542"),
                            Description = "Swaddle your newborn to provide a sense of security and improve sleep. Use a breathable blanket, ensuring hips remain loose to prevent hip dysplasia. Stop swaddling once your baby shows signs of rolling over for safety reasons.",
                            Title = "Swaddling Tips"
                        },
                        new
                        {
                            Id = new Guid("2e383cf7-95be-4410-b121-e35dad9f57d4"),
                            Description = "Soothe a colicky baby by using gentle rocking motions, white noise, and tummy massages. Hold your baby upright after feedings, try warm baths, and maintain a calm environment to help reduce discomfort and frequent crying episodes.",
                            Title = "Colic Soothing"
                        },
                        new
                        {
                            Id = new Guid("a4cf960d-d4e0-4109-b8d6-859bed95c6fe"),
                            Description = "Involve siblings and partners in daily baby care routines like feeding, diaper changes, and playtime. This strengthens family bonds, fosters teamwork, and helps everyone feel included in the baby's growth and development journey.",
                            Title = "Family Bonding"
                        },
                        new
                        {
                            Id = new Guid("451cdfff-da22-410d-b96e-09f60914242b"),
                            Description = "Avoid exposing babies under 18 months to screens, including TVs, tablets, and smartphones. Instead, focus on interactive play, reading, and real-world experiences to promote healthy brain development, language skills, and emotional growth.",
                            Title = "Limit Screen Time"
                        },
                        new
                        {
                            Id = new Guid("3ca33b06-3498-42b2-b20e-b073b4af4686"),
                            Description = "Ease your baby's separation anxiety by practicing short, calm goodbyes and reassuring them that you'll return. Establish consistent routines, introduce comfort objects like a favorite toy, and gradually increase time apart to help build confidence.",
                            Title = "Dealing with Separation Anxiety"
                        },
                        new
                        {
                            Id = new Guid("1bd17470-35c0-4382-a837-73b3a2df773d"),
                            Description = "Offer a variety of healthy snack options like soft fruits, steamed vegetables, yogurt, and whole grain crackers. Avoid sugary and processed foods, and encourage self-feeding to help your baby develop fine motor skills and healthy eating habits.",
                            Title = "Healthy Snacks"
                        },
                        new
                        {
                            Id = new Guid("7bc67bf3-855a-45fc-b832-4ead7018d868"),
                            Description = "Never leave your baby unattended during bath time, even for a moment. Always check that the water temperature is lukewarm, use non-slip mats, and keep bathing supplies within reach to ensure a safe and enjoyable experience.",
                            Title = "Bath Time Safety"
                        },
                        new
                        {
                            Id = new Guid("30bcc1f3-07d9-4a8b-80bb-a1de3dac0d74"),
                            Description = "Talk, sing, and read to your baby every day to help develop their language skills. Use simple words, repeat sounds, and engage in conversations even if they can't respond yet, fostering early communication and cognitive development.",
                            Title = "Early Language Development"
                        },
                        new
                        {
                            Id = new Guid("49955950-71c1-4da2-bda4-1dfb4b6904aa"),
                            Description = "Introduce new foods gradually, one at a time, and monitor for signs of allergic reactions like rashes, vomiting, or difficulty breathing. Always consult your pediatrician about the best time to introduce common allergens like peanuts and eggs.",
                            Title = "Allergy Awareness"
                        },
                        new
                        {
                            Id = new Guid("0b6875cc-d7f3-4482-9c78-7338daadf13e"),
                            Description = "Place your baby on their back to sleep on a firm mattress without loose bedding, pillows, or stuffed animals. This reduces the risk of sudden infant death syndrome (SIDS) and creates a safer sleeping environment.",
                            Title = "Safe Sleeping"
                        },
                        new
                        {
                            Id = new Guid("b0a0c2d3-f93f-4b51-8b9d-c65a15999993"),
                            Description = "Secure heavy furniture to walls, use outlet covers, install safety gates, and keep sharp objects, cleaning supplies, and small items out of reach. Regularly inspect your home for potential hazards as your baby becomes more mobile.",
                            Title = "Childproofing"
                        },
                        new
                        {
                            Id = new Guid("0f8c2d83-7bc7-46f2-bab2-daccfa3e5f0a"),
                            Description = "Incorporate textures, sounds, and colors into your baby's playtime to stimulate their senses and encourage cognitive development. Activities like playing with soft fabrics, musical toys, and colorful stacking blocks help support learning and fine motor skills.",
                            Title = "Sensory Play"
                        },
                        new
                        {
                            Id = new Guid("1923628a-903b-4e19-8539-4ffd71fe4d6e"),
                            Description = "When outdoors, protect your baby from direct sunlight using baby-safe sunscreen, wide-brimmed hats, and lightweight clothing. Limit sun exposure during peak hours, and always use a stroller with a sunshade or find shaded areas.",
                            Title = "Sun Safety"
                        },
                        new
                        {
                            Id = new Guid("363a3924-3671-46e0-8382-5909e4702646"),
                            Description = "Respond empathetically to your baby's emotions by offering comfort and affection when they are upset. Positive interactions, like smiling, cuddling, and playing, help build trust, emotional security, and healthy social skills over time.",
                            Title = "Emotional Development"
                        },
                        new
                        {
                            Id = new Guid("184b3172-0c93-45a8-a000-c1bd7f9bfed7"),
                            Description = "Place toys just out of your baby's reach on a soft surface to motivate them to crawl. This helps strengthen their muscles, improve coordination, and develop important motor skills necessary for walking and other physical activities.",
                            Title = "Encouraging Crawling"
                        },
                        new
                        {
                            Id = new Guid("7e14b154-8244-455b-8a5c-b96d124b1ddb"),
                            Description = "Create predictable routines for feeding, sleeping, and playtime to help your baby feel secure and understand what to expect. Consistency promotes healthy habits, reduces anxiety, and supports better sleep and overall development.",
                            Title = "Consistent Routines"
                        },
                        new
                        {
                            Id = new Guid("121ac25e-60aa-446b-a37a-6ba8baa0ef7c"),
                            Description = "Use a rear-facing car seat for your baby, following the manufacturer's guidelines, and ensure it's properly installed. Plan for frequent breaks during long trips for feeding and diaper changes, and never leave your baby unattended in the car.",
                            Title = "Traveling Safely"
                        },
                        new
                        {
                            Id = new Guid("95d75535-30e7-4582-bbae-1ccae505c1bc"),
                            Description = "Always check bath water temperature to ensure it's lukewarm and monitor your home's room temperature to prevent overheating. Dress your baby in appropriate layers for the weather and avoid heavy blankets during sleep for safety.",
                            Title = "Temperature Checks"
                        },
                        new
                        {
                            Id = new Guid("85fa0d5e-1786-458f-9ec3-8b1229601403"),
                            Description = "Give your toddler age-appropriate tasks like self-feeding or tidying toys to foster independence and build confidence. Encourage problem-solving and decision-making by offering simple choices, helping them develop important life skills.",
                            Title = "Encouraging Independence"
                        },
                        new
                        {
                            Id = new Guid("ec2c57c6-a69d-4cb0-b809-445bd4123a8e"),
                            Description = "Enhance your baby's vocabulary by naming objects during playtime, reading books with simple words, and describing everyday activities. Repetition and exposure to language help strengthen communication skills and encourage early word recognition.",
                            Title = "Building Vocabulary"
                        },
                        new
                        {
                            Id = new Guid("ac9188d2-b4d7-4177-9cf0-d8171416e305"),
                            Description = "Offer your baby a variety of fruits, vegetables, grains, and proteins to promote a balanced diet. Avoid added sugars and overly processed foods, and focus on nutrient-dense options to support healthy growth and development.",
                            Title = "Balanced Diet"
                        },
                        new
                        {
                            Id = new Guid("360b59ef-7f82-4211-b5aa-21e1b6b0afdd"),
                            Description = "Praise your baby's positive behaviors with smiles, claps, or words of encouragement. This reinforces good habits and builds self-esteem, helping your baby feel valued and motivated to repeat those behaviors in the future.",
                            Title = "Positive Reinforcement"
                        },
                        new
                        {
                            Id = new Guid("04c2532d-c204-41a5-87f8-eae165b07f37"),
                            Description = "Recognize and celebrate your baby's achievements, no matter how small, to boost their confidence. Applauding milestones like first steps, new words, or successful potty training encourages continued learning and strengthens your emotional connection.",
                            Title = "Celebrating Small Wins"
                        });
                });

            modelBuilder.Entity("SavedProduct", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("SavedProducts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("project_BLL.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("project_BLL.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project_BLL.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("project_BLL.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("project_BLL.Identity.AppUser", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("project_DAL.Entities.BabyRecord", b =>
                {
                    b.HasOne("project_BLL.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("project_DAL.Entities.Message", b =>
                {
                    b.HasOne("project_BLL.Identity.AppUser", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("project_DAL.Entities.MessageDeleted", b =>
                {
                    b.HasOne("project_DAL.Entities.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("project_BLL.Identity.AppUser", "User")
                        .WithMany("MessagesDeleted")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("project_DAL.Entities.MotherGuids.UserTip", b =>
                {
                    b.HasOne("project_DAL.Identity.Tip", "Tip")
                        .WithMany("UserTips")
                        .HasForeignKey("TipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project_BLL.Identity.AppUser", "User")
                        .WithMany("UserTips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SavedProduct", b =>
                {
                    b.HasOne("Product", "Product")
                        .WithMany("SavedByUsers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project_BLL.Identity.AppUser", "User")
                        .WithMany("SavedProducts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Navigation("SavedByUsers");
                });

            modelBuilder.Entity("project_BLL.Identity.AppUser", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("MessagesDeleted");

                    b.Navigation("Products");

                    b.Navigation("SavedProducts");

                    b.Navigation("UserTips");
                });

            modelBuilder.Entity("project_DAL.Identity.Tip", b =>
                {
                    b.Navigation("UserTips");
                });
#pragma warning restore 612, 618
        }
    }
}
